### ISSUE TITLE
Issue with Average Pooling?

### ISSUE THREAD

**Issue by gilbblig** [NervanaSystems/he-transformer#229]
Hi & Thanks for this great library!

I've been playing around with it for a couple of days, but I faced some issues when trying to integrate average pooling and having the encryption flags set.

In your MNIST-Cryptonets example the suggested test via 

```
NGRAPH_ENCRYPT_DATA=1 \
NGRAPH_HE_SEAL_CONFIG=../../test/model/he_seal_ckks_config_N13_L7.json \
NGRAPH_TF_BACKEND=HE_SEAL \
python test.py --batch_size=4096
```

utilizes a subset of the network trained by calling train.py. This subset discards the average pooling layer. I updated the code in common.py and use it now for training as well as testing. It works when I don't include an average pooling layer, and it works when nothing is encrypted. As soon as I utilize the above encryption configuration, it crashes with the appended message.

I'm running it on a system with 4 CPU's and 26 GB of memory, which I hope is sufficient for the purpose, especially when testing on just 1 image.

How could this be tackled? Thanks in advance!

```

2019-07-05 10:25:47.168665: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2300000000 Hz
2019-07-05 10:25:47.170316: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x4cf6860 executing computations on platform Host. Devices:
2019-07-05 10:25:47.170370: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
/
| Encryption parameters :
|   scheme: CKKS
|   poly_modulus_degree: 8192
|   coeff_modulus size: 180 (30 + 24 + 24 + 24 + 24 + 24 + 30) bits
\
[INFO] 2019-07-05T10:25:47z src/seal/he_seal_backend.cpp 84	Scale 1.67608e+07
[INFO] 2019-07-05T10:25:47z src/seal/he_seal_executable.cpp 142	Setting parameters and results
[INFO] 2019-07-05T10:25:47z src/seal/he_seal_executable.cpp 144	Parameters size 1
[INFO] 2019-07-05T10:25:47z src/seal/he_seal_executable.cpp 476	Encrypting data
[INFO] 2019-07-05T10:25:47z src/seal/he_seal_executable.cpp 479	Batching data with batch size 1
[INFO] 2019-07-05T10:25:47z src/seal/he_seal_executable.cpp 496	Processing server inputs
[INFO] 2019-07-05T10:25:47z src/seal/he_seal_executable.cpp 521	Encrypting parameter 0
[INFO] 2019-07-05T10:25:50z src/seal/he_seal_executable.cpp 538	Done encrypting parameter
2019-07-05 10:26:01.741378: I /home/ron/he-transformer_new/he-transformer/build/ext_ngraph_tf/src/ext_ngraph_tf/src/ngraph_utils.cc:252] Serializing graph to: tf_function_error_ngraph_cluster_0.json

Traceback (most recent call last):
  File "/home/ron/he-transformer_new/he-transformer/build/ext_ngraph_tf/src/ext_ngraph_tf/build_cmake/venv-tf-py3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/home/ron/he-transformer_new/he-transformer/build/ext_ngraph_tf/src/ext_ngraph_tf/build_cmake/venv-tf-py3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/ron/he-transformer_new/he-transformer/build/ext_ngraph_tf/src/ext_ngraph_tf/build_cmake/venv-tf-py3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InternalError: Caught exception while executing nGraph computation: scale mismatch

	 [[{{node ngraph_cluster_0}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test2.py", line 144, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/home/ron/he-transformer_new/he-transformer/build/ext_ngraph_tf/src/ext_ngraph_tf/build_cmake/venv-tf-py3/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "test2.py", line 121, in main
    test_mnist_cnn(FLAGS)
  File "test2.py", line 80, in test_mnist_cnn
    y_conv_val = y_conv.eval(feed_dict={x: x_test, y_: y_test})
  File "/home/ron/he-transformer_new/he-transformer/build/ext_ngraph_tf/src/ext_ngraph_tf/build_cmake/venv-tf-py3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 695, in eval
    return _eval_using_default_session(self, feed_dict, self.graph, session)
  File "/home/ron/he-transformer_new/he-transformer/build/ext_ngraph_tf/src/ext_ngraph_tf/build_cmake/venv-tf-py3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 5181, in _eval_using_default_session
    return session.run(tensors, feed_dict)
  File "/home/ron/he-transformer_new/he-transformer/build/ext_ngraph_tf/src/ext_ngraph_tf/build_cmake/venv-tf-py3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/ron/he-transformer_new/he-transformer/build/ext_ngraph_tf/src/ext_ngraph_tf/build_cmake/venv-tf-py3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/ron/he-transformer_new/he-transformer/build/ext_ngraph_tf/src/ext_ngraph_tf/build_cmake/venv-tf-py3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/home/ron/he-transformer_new/he-transformer/build/ext_ngraph_tf/src/ext_ngraph_tf/build_cmake/venv-tf-py3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: Caught exception while executing nGraph computation: scale mismatch

	 [[{{node ngraph_cluster_0}}]]

```

**Comment by fboemer** [comment]
A few comments:
* >I'm running it on a system with 4 CPU's and 26 GB of memory, which I hope is sufficient for the purpose, especially when testing on just 1 image.

This should be sufficient for small MNIST examples; Note, our performance is *identical* when testing on just 1 image, or 4096 images, due to our use of SIMD packing (see our [paper](https://arxiv.org/pdf/1810.10121.pdf))

* Would you attach the `tf_function_error_ngraph_cluster_0.json` that seems to have been generated? This will help us debug.
