### ISSUE TITLE
 NGRAPH_TF_BACKEND: HE_SEAL is not supported

### ISSUE THREAD

**Issue by xiaoxiaowan233** [NervanaSystems/he-transformer#235]
I run ax.py using `  NGRAPH_TF_BACKEND=HE_SEAL python ax.py`. However i got
```
Traceback (most recent call last):
  File "ax.py", line 26, in <module>
    f_val = sess.run(f, feed_dict={b: np.ones((1, 2))})
  File "/home/xiaoxiaowan/he-transformer/build/ext_ngraph_tf/src/ext_ngraph_tf/build_cmake/venv-tf-py3/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/xiaoxiaowan/he-transformer/build/ext_ngraph_tf/src/ext_ngraph_tf/build_cmake/venv-tf-py3/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/xiaoxiaowan/he-transformer/build/ext_ngraph_tf/src/ext_ngraph_tf/build_cmake/venv-tf-py3/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/home/xiaoxiaowan/he-transformer/build/ext_ngraph_tf/src/ext_ngraph_tf/build_cmake/venv-tf-py3/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: NGRAPH_TF_BACKEND: HE_SEAL is not supported
```

Thanks

**Comment by xiaoxiaowan233** [comment]
I solve it.
When run `make install`, i met with [#233](https://github.com/NervanaSystems/he-transformer/issues/233), but i soved it by simply  using `mkdir - p ./build/ext_ngraph_tf/src/ext_ngraph_tf .../ngraph_bridge`
 `NGRAPH_TF_BACKEND: HE_SEAL is not supported `  may appear  due to  `mkdir - p ...`
